version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bookstore_inventory" ]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bookstore_inventory
    ports:
      - '5433:5432'

  app:
    container_name: azul-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/bookstore_inventory
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
